name: CaffeinRPG-Status
version: Experimental
main: caffein.momineko.core.CaffeinCore
api-version: 1.17
authors: [ MomiNeko ]
description: CaffeinRPG-Status

commands:
  CaffeinStatus:
    aliases: cs
    description: CaffeingRPG-Status
    usage: /<command>